export const biharEngineeringColleges = [
    "Bhagalpur College of Engineering (BCE), Bhagalpur",
    "Muzaffarpur Institute of Technology (MIT), Muzaffarpur",
    "Gaya College of Engineering (GCE), Gaya",
    "Darbhanga College of Engineering (DCE), Darbhanga",
    "Motihari College of Engineering (MCE), Motihari",
    "Nalanda College of Engineering (NCE), Chandi",
    "Lok Nayak Jai Prakash Institute of Technology (LNJPIT), Chapra",
    "Vidya Vihar Institute of Technology (VVIT), Purnea",
    "Bakhtiyarpur College of Engineering (BCE), Bakhtiyarpur",
    "Sitamarhi Institute of Technology (SIT), Sitamarhi",
    "Supaul College of Engineering (SCE), Supaul",
    "Purnea College of Engineering (PCE), Purnea",
    "Saharsa College of Engineering (SCE), Saharsa",
    "Government Engineering College (GEC), Banka",
    "Government Engineering College (GEC), Vaishali",
    "Government Engineering College (GEC), Jamui",
    "Government Engineering College (GEC), Nawada",
    "Government Engineering College (GEC), Kishanganj",
    "Government Engineering College (GEC), Munger",
    "Government Engineering College (GEC), Sheohar",
    "Government Engineering College (GEC), West Champaran",
    "Government Engineering College (GEC), Aurangabad",
    "Government Engineering College (GEC), Kaimur",
    "Government Engineering College (GEC), Gopalganj",
    "Government Engineering College (GEC), Madhubani",
    "Government Engineering College (GEC), Siwan",
    "Government Engineering College (GEC), Jehanabad",
    "Government Engineering College (GEC), Arwal",
    "Government Engineering College (GEC), Khagaria",
    "Government Engineering College (GEC), Buxar",
    "Government Engineering College (GEC), Bhojpur",
    "Government Engineering College (GEC), Sheikhpura",
    "Government Engineering College (GEC), Lakhisarai",
    "Government Engineering College (GEC), Samastipur",
    "Other"
];
